name: Update Include.js on Site
on:
  push:
    paths:
      - 'JavaScript/include.js' # Path to the file you want to track for syncronization
env:
  #Local Repo Settings 
  localPath: 'JavaScript/include.js'
  #Remote Repo Settings
  repoOwner: 'pyrophoenix100'
  repoName: 'pyrophoenix100.github.io'
  remotePath: 'scripts/include.js'
  commitMessage: 'Push Include.js to live'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Get SHA of File
          uses: actions/github-script@v4
          id: file-sha
          with:
            script: |
              const response = await github.repos.getContent({
                owner: '${{ env.repoOwner }}',
                repo: '${{ env.repoName }}',
                path: '${{ env.remotePath }}'
              });
              core.setOutput('SHA', response.data.sha);
        - name: Overwrite include.js
          uses: actions/github-script@v4
          with:
            script: |
              const fs = require('fs')
              const content = fs.readFileSync('./${{ env.localPath }}', 'utf8')
              github.repos.createOrUpdateFileContents({
                owner: '${{ env.repoOwner }}',
                repo: '${{ env.repoName }}',
                path: '${{ env.remotePath }}',
                message: '${{ env.commitMessage }}',
                content: Buffer.from(content).toString('base64'),
                sha: '${{ steps.file-sha.outputs.SHA }}'
              })
            github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
