name: Update Include.js on Site
on:
  push:
    paths:
      - 'JavaScript/includes.js'
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Overwrite include.js
          uses: actions/github-script@v4
          with:
            script: |
              const fs = require('fs')
              const path = require('path')
              fs.readdir('.', (err, files) => {
                if (err) {
                  core.warning(err)
                  return
                }
                core.warning(files)
              })
            github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
