name: Update Include.js on Site
on:
  push:
    paths:
      - 'JavaScript/include.js' # Path to the file you want to track for syncronization
env:
  repoOwner: pyrophoenix100
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Get SHA of File
          uses: actions/github-script@v4
          id: file-sha
          with:
            script: |
              const fs = require('fs')
              const response = await github.repos.getContent({
                owner: '${{ env.repoOwner }}',
                repo: 'pyrophoenix100.github.io',
                path: 'scripts/include.js'
              });
              core.setOutput('SHA', response.data.sha);
        - name: Overwrite include.js
          uses: actions/github-script@v4
          with:
            script: |
              const fs = require('fs')
              const path = require('path')
              const content = fs.readFileSync('./JavaScript/include.js', 'utf8')
              github.repos.createOrUpdateFileContents({
                owner: 'Pyrophoenix100',
                repo: 'pyrophoenix100.github.io',
                path: 'scripts/include.js',
                message: 'Syncronize include.js',
                content: Buffer.from(content).toString('base64'),
                sha: '${{ steps.file-sha.outputs.SHA }}'
              })
            github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
