name: Update Include.js on Site
on:
  push:
    paths:
      - 'JavaScript/includes.js'
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Overwrite include.js
          uses: actions/github-script@v4
          with:
            script: |
              const fs = require('fs')
              const content = fs.readFileSync('JavaScript/include.js', 'utf8')
              github.repos.createOrUpdateFileContents({
                owner: 'Pyrophoenix100',
                repo: 'pyrophoenix100.github.io',
                path: '/scripts/include.js',
                message: 'Update include.js',
                content: Buffer.from(content).toString('base64'),
                sha: context.payload.after
              })
            token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
